### ISSUE TITLE
Airdrop Time Mismatch

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-starter-subscription-airdrops#17]
## Issue
UTC times aren't aligned between scheduling the drop and airdropping the NFTs.

## Requirement
- [x] Create a drop 1 hour in the future and confirm times returned by the API are correct
- [x] Audit the time produced by calling Utc::now in the airdrop script

**Comment by mpwsh** [comment]
Times match correctly. all are UTC, the problem is the dates. 


Selector in the console shows one thing and then on the review page you get the previous day, which is whats actually saved on the DB



![Image](https://github.com/holaplex/hub-starter-subscription-airdrops/assets/13471075/e8047a42-1357-43d3-a1b2-6d9e8a97f54b)



Review page



![Image](https://github.com/holaplex/hub-starter-subscription-airdrops/assets/13471075/fab1e5a2-a8f0-4c31-b396-8666bd9fb44a)


06 PM my time is 9PM UTC.

From airdrop script:
```bash
[2023-07-19T18:18:27Z INFO  airdrop] Current time: 2023-07-19 18:18:27.786765 UTC -- Drop scheduled for time: 2023-07-18 21:00:00 UTC
```

**Comment by mpwsh** [comment]
PR Fixing wrong day when creating drops.

https://github.com/holaplex/hub/pull/249

**Comment by kespinola** [comment]
done.
